---
- name: validate kong
  shell: >
      /usr/local/bin/kong check {{ kong_conf_dir }}/kong.conf

- name: reload kong
  service:
    name: kong
    state: reloaded

- name: restart kong
  service:
    name: kong
    state: restarted

- name: start kong
  service:
    name: kong
    state: started

- name: stop kong
  service:
    name: kong
    state: stopped
